# Generated by Django 4.1.3 on 2022-11-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "page",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Feeling"), (2, "Reason"), (3, "Result")],
                        default=1,
                    ),
                ),
                (
                    "feeling",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Not well"), (2, "Feeling frisky"), (3, "Sad")],
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Health"), (2, "Money"), (3, "Relationship")],
                        null=True,
                    ),
                ),
            ],
        ),
    ]
